import slugify from '../utils/slugify'
import {
  orderRankField,
  orderRankOrdering,
} from '@sanity/orderable-document-list';

export default {
  title: "Project",
  name: 'project',
  type: "document",
  orderings: [orderRankOrdering],
  fields: [
    {
      title: "Title",
      description: "The name of this project",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    orderRankField({ type: 'project', hidden: true }),
    {
      title: 'Tags',
      name: 'tags',
      description: 'Tags for this project, eg: "Greenbelt Homes", "BIF", etc',
      type: 'array', 
      of: [{type: 'string'}],
    },
    {
      title: 'Meta Text',
      name: 'meta',
      description: 'Meta Texts for this project, eg: "Luxury Housing Development", "£4m GDV", etc',
      type: 'array', 
      of: [{type: 'string'}],
    },
    {
      title: 'Text', 
      name: 'text',
      type: 'contentSimple', 
    },
    {
      title: 'Image(s)',
      name: 'images',
      type: 'array',
      description: "The image(s) for this project, the first image will show by default",
      of: [
        {
          type: 'defaultImage', title: 'Image',
        },
      ],
      options: {
        layout: 'grid',
      },
      validation: Rule => Rule.required().min(1).max(20)
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: (doc) => {
          let titleSlug = ''
          let campaignSlug = ''
          if (doc.title) {
            titleSlug = `${doc.title}`
          } else {
            titleSlug = ''
          }

          if (doc.campaignTitle) {
            campaignSlug = `-${doc.campaignTitle}`
          } else {
            campaignSlug = ''
          }

          return `${titleSlug}${campaignSlug}`;
        },
        maxLength: 96,
        slugify: (input) => slugify(`${input}`)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    }
  ],
  preview: {
    select: {
      title: 'title',
      media: 'images.0'
    }
  }
}